name: Pylint Check

on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger this workflow

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --output-format=json my_project_directory/ > pylint-report.json
    - name: Upload Pylint Report as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pylint-report
        path: pylint-report.json
